### ISSUE TITLE
Question: How do you run the SQL script? 

### ISSUE THREAD

**Issue by martinandersen3d** [nuitsjp/AdventureWorks-for-SQLite#1]
I'm not sure how to run the script.

**What is the correct process to run this script?** 

- I'm using "DB Browser for SQLite"

When I try to run it I get this error:

![image](https://user-images.githubusercontent.com/19984581/187892050-c719c451-b60a-4bd7-9cad-7378e488be5d.png)
 
By the way, I did manually import some of the fields and build the database here:
https://github.com/martinandersen3d/AdventureWorks-for-SQLite

I'm still missing two tables I'm having issues with creating:
"ProductDescription" and "ProductModelProductDescription"

**Comment by nuitsjp** [comment]
This is the topic of SQLite usage, not this repository. 
Also, I don't use "DB Browser for SQLite", so I can't answer the above directly.

If you want to rebuild it manually, run "CreateAdventureWorks.cmd".

If that is also difficult, please use the released version.
